name: CI with GitHub

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

on:
  schedule:
    - cron: '26 13 * * *'
  push:
    branches: [ main ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ main ]

env:
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
          
      - name: Setup Java JDK
        uses: actions/setup-java@v2.3.1
        with:
          java-version: '11'
          distribution: 'adopt'
          
      - name: Build Eureka Service Image
        working-directory: ./eureka-service
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build API Gateway Image
        working-directory: ./api-gateway
        run: mvn spring-boot:build-image -DskipTests
        
      - name: Build Cambio Service Jar
        working-directory: ./cambio-service
        run: mvn clean package -DskipTests
        
      - name: Build Book Service Jar
        working-directory: ./book-service
        run: mvn clean package -DskipTests
        
      - name: Docker Compose Build
        working-directory: .
        run: docker-compose build
        
      - name: Push to Docker Hub
        run: 
          docker tag ${{ secrets.DOCKER_USERNAME }}/eureka-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/eureka-service:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/eureka-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/eureka-service:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/api-gateway:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/cambio-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/cambio-service:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/cambio-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest
          docker tag ${{ secrets.DOCKER_USERNAME }}/book-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/book-service:${{github.run_id}}
          docker tag ${{ secrets.DOCKER_USERNAME }}/book-service:0.0.1-SNAPSHOT ${{ secrets.DOCKER_USERNAME }}/book-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/eureka-service:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/eureka-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/api-gateway:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/cambio-service:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/cambio-service:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:${{github.run_id}}
          docker push ${{ secrets.DOCKER_USERNAME }}/book-service:latest
